import { Language, Level } from './types';

export const APP_VERSION = '1.1.0';

// --- EMAILJS CONFIGURATION ---
export const EMAILJS_CONFIG = {
  SERVICE_ID: 'service_ryecfaz',
  TEMPLATE_ID: 'template_ocdt3fp',
  PUBLIC_KEY: 'bvtCCQRJeKTyi5Dd8'
};

export const LEVEL_THRESHOLDS = {
  [Level.BRONZE]: 0,
  [Level.SILVER]: 300,
  [Level.GOLD]: 800,
};

export const DAILY_TIPS = {
  [Language.EN]: [
    "Track every dollar you spend for one week to see where your money goes.",
    "Use the 24-hour rule: wait 24 hours before buying non-essential items.",
    "Student discounts are everywhere—always ask before you pay!",
    "Pay yourself first: save 10% of any income before spending.",
    "Cancel subscriptions you haven't used in the last month."
  ],
  [Language.ZH_HK]: [
    "記下這週花的每一元，看看錢都去哪了。",
    "使用24小時法則：購買非必需品前先等24小時。",
    "學生優惠無處不在——付款前記得問！",
    "先支付給自己：在消費前先儲起10%的收入。",
    "取消上個月沒使用過的訂閱服務。"
  ],
  [Language.ZH_CN]: [
    "记下这周花的每一元，看看钱都去哪了。",
    "使用24小时法则：购买非必需品前先等24小时。",
    "学生优惠无处不在——付款前记得问！",
    "先支付给自己：在消费前先存起10%的收入。",
    "取消上个月没使用过的订阅服务。"
  ]
};

export const IFEC_TOPICS = {
  [Level.BRONZE]: [
    "Budgeting basics for students",
    "Needs vs Wants",
    "Tracking daily expenses",
    "Student Octopus card usage",
    "Saving for short term goals"
  ],
  [Level.SILVER]: [
    "Credit card interest rates",
    "Student loans and Grant/Loan repayment",
    "Buy Now Pay Later risks",
    "Online payment security",
    "Credit score importance"
  ],
  [Level.GOLD]: [
    "MPF basics for part-time jobs",
    "Compound interest",
    "Basic investment risks (Stocks vs Bonds)",
    "Insurance for young adults",
    "Financial freedom concepts"
  ]
};

export const TRANSLATIONS = {
  [Language.EN]: {
    appName: "$mart Journey",
    tagline: "Master your financial future",
    login: "Login",
    register: "Register",
    logout: "Logout",
    dashboard: "Dashboard",
    play: "Play & Learn",
    profile: "Profile",
    advisor: "Dr. $mart",
    email: "Email Address",
    password: "Password",
    name: "Display Name",
    submit: "Submit",
    bronze: "Bronze",
    silver: "Silver",
    gold: "Gold",
    currentLevel: "Current Level",
    xp: "XP",
    nextLevel: "Next Level",
    generateQuestion: "Start Challenge",
    loading: "Consulting Financial Expert...",
    correct: "Correct!",
    incorrect: "Incorrect.",
    explanation: "Expert Tip:",
    next: "Next Challenge",
    changePassword: "Change Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    welcomeBack: "Welcome back",
    loginSubtitle: "Welcome back to $mart Journey",
    registerSubtitle: "Start your financial journey today",
    registerSuccess: "Registration successful! Your temporary password is:",
    registerNote: "In a real app, this would be emailed to you.",
    passwordChanged: "Password changed successfully.",
    error: "Error",
    levelUp: "Level Up! You are now",
    guest: "Guest",
    topic: "Topic",
    dailyTip: "Daily Insight",
    tip: "Tip",
    completed: "Completed",
    locked: "Locked",
    current: "Current",
    advisorIntro: "Hi! I'm Dr. $mart. Ask me anything about student finance, loans, or savings!",
    typeMessage: "Type your question...",
    send: "Send",
    speaking: "Speaking...",
    // Module/Lesson UI
    page: "Page",
    of: "of",
    module: "Module",
    backToModules: "Back to Modules",
    keyTakeaways: "Key Takeaways",
    realLifeScenario: "Real Life Scenario",
    index: "Index",
    close: "Close",
    previous: "Previous",
    finish: "Finish",
    // Navigation
    home: "Home",
    learn: "Learn",
    games: "Games",
    exam: "Exam",
    askAi: "Ask AI",
    // Dashboard
    studentId: "Student ID",
    hi: "Hi",
    welcomeMessage: "Ready to boost your financial IQ today?",
    totalXp: "Total XP Score",
    levelProgress: "Level Progress",
    cheatSheet: "Cheat Sheet",
    dailyTipLabel: "Daily Tip",
    myRank: "My Rank",
    rank: "Rank",
    continueLearning: "Continue Learning",
    continueLearningDesc: "Jump back into your lessons",
    playSimulations: "Play Simulations",
    playSimulationsDesc: "Test your skills in scenarios"
  },
  [Language.ZH_HK]: {
    appName: "$mart Journey",
    tagline: "掌握你的理財未來",
    login: "登入",
    register: "註冊",
    logout: "登出",
    dashboard: "儀表板",
    play: "學習挑戰",
    profile: "個人檔案",
    advisor: "Dr. $mart 顧問",
    email: "電子郵件",
    password: "密碼",
    name: "顯示名稱",
    submit: "提交",
    bronze: "銅牌",
    silver: "銀牌",
    gold: "金牌",
    currentLevel: "當前等級",
    xp: "經驗值",
    nextLevel: "下一等級",
    generateQuestion: "開始挑戰",
    loading: "正在諮詢理財專家...",
    correct: "答對了！",
    incorrect: "答錯了。",
    explanation: "專家提示：",
    next: "下一個挑戰",
    changePassword: "更改密碼",
    newPassword: "新密碼",
    confirmPassword: "確認密碼",
    welcomeBack: "歡迎回來",
    loginSubtitle: "歡迎回到 $mart Journey",
    registerSubtitle: "立即開始您的理財之旅",
    registerSuccess: "註冊成功！您的臨時密碼是：",
    registerNote: "在真實應用程式中，這將發送至您的電子郵件。",
    passwordChanged: "密碼已成功更改。",
    error: "錯誤",
    levelUp: "升級！你現在是",
    guest: "訪客",
    topic: "主題",
    dailyTip: "每日理財",
    tip: "提示",
    completed: "已完成",
    locked: "未解鎖",
    current: "當前",
    advisorIntro: "你好！我是 Dr. $mart。關於學生理財、學費貸款或儲蓄的問題，隨便問我！",
    typeMessage: "輸入你的問題...",
    send: "發送",
    speaking: "正在說話...",
    // Module/Lesson UI
    page: "頁",
    of: "/",
    module: "單元",
    backToModules: "返回單元列表",
    keyTakeaways: "重點摘要",
    realLifeScenario: "真實案例",
    index: "目錄",
    close: "關閉",
    previous: "上一頁",
    finish: "完成",
    // Navigation
    home: "首頁",
    learn: "學習",
    games: "遊戲",
    exam: "考試",
    askAi: "問AI",
    // Dashboard
    studentId: "學生證編號",
    hi: "你好",
    welcomeMessage: "準備好提升你的理財智商了嗎？",
    totalXp: "總經驗值",
    levelProgress: "等級進度",
    cheatSheet: "速查表",
    dailyTipLabel: "每日提示",
    myRank: "我的排名",
    rank: "排名",
    continueLearning: "繼續學習",
    continueLearningDesc: "回到你的課程",
    playSimulations: "模擬遊戲",
    playSimulationsDesc: "在場景中測試你的技巧"
  },
  [Language.ZH_CN]: {
    appName: "$mart Journey",
    tagline: "掌握你的理财未来",
    login: "登录",
    register: "注册",
    logout: "登出",
    dashboard: "仪表板",
    play: "学习挑战",
    profile: "个人资料",
    advisor: "Dr. $mart 顾问",
    email: "电子邮件",
    password: "密码",
    name: "显示名称",
    submit: "提交",
    bronze: "铜牌",
    silver: "银牌",
    gold: "金牌",
    currentLevel: "当前等级",
    xp: "经验值",
    nextLevel: "下一等级",
    generateQuestion: "开始挑战",
    loading: "正在咨询理财专家...",
    correct: "答对了！",
    incorrect: "答错了。",
    explanation: "专家提示：",
    next: "下一个挑战",
    changePassword: "更改密码",
    newPassword: "新密码",
    confirmPassword: "确认密码",
    welcomeBack: "欢迎回来",
    loginSubtitle: "欢迎回到 $mart Journey",
    registerSubtitle: "立即开始您的理财之旅",
    registerSuccess: "注册成功！您的临时密码是：",
    registerNote: "在真实应用程序中，这将发送至您的电子邮件。",
    passwordChanged: "密码已成功更改。",
    error: "错误",
    levelUp: "升级！你现在是",
    guest: "访客",
    topic: "主题",
    dailyTip: "每日理财",
    tip: "提示",
    completed: "已完成",
    locked: "未解锁",
    current: "当前",
    advisorIntro: "你好！我是 Dr. $mart。关于学生理财、学费贷款或储蓄的问题，随便问我！",
    typeMessage: "输入你的问题...",
    send: "发送",
    speaking: "正在说话...",
    // Module/Lesson UI
    page: "页",
    of: "/",
    module: "单元",
    backToModules: "返回单元列表",
    keyTakeaways: "重点摘要",
    realLifeScenario: "真实案例",
    index: "目录",
    close: "关闭",
    previous: "上一页",
    finish: "完成",
    // Navigation
    home: "首页",
    learn: "学习",
    games: "游戏",
    exam: "考试",
    askAi: "问AI",
    // Dashboard
    studentId: "学生证编号",
    hi: "你好",
    welcomeMessage: "准备好提升你的理财智商了吗？",
    totalXp: "总经验值",
    levelProgress: "等级进度",
    cheatSheet: "速查表",
    dailyTipLabel: "每日提示",
    myRank: "我的排名",
    rank: "排名",
    continueLearning: "继续学习",
    continueLearningDesc: "回到你的课程",
    playSimulations: "模拟游戏",
    playSimulationsDesc: "在场景中测试你的技巧"
  }
};